### ISSUE TITLE
Проблемка при компиляции с исходников (Z-Stack 3.0.2 и Embedded Workbench 8.1) что я пропустил?

### ISSUE THREAD

**Issue by v222008** [diyruz/geiger#2]
![2020-08-02 (1)](https://user-images.githubusercontent.com/4614427/89121206-9d3eb600-d4c5-11ea-86dd-9fed7b08e2d8.png)

**Comment by nurikk** [comment]
По структуре файлов могу сказать что вы точно не последнюю версию исходников скачали, так же рекомендую пользоваться клиентом git для скачивания исходников, а не экспортировать их как zip файл.
Если опыта пользования git нет, то рекомендую использовать [официальный клиент от гитхаба](https://desktop.github.com/) с ним все будет просто и понятно

**Comment by v222008** [comment]
> По структуре файлов могу сказать что вы точно не последнюю версию исходников скачали, так же рекомендую пользоваться клиентом git для скачивания исходников, а не экспортировать их как zip файл.
> Если опыта пользования git нет, то рекомендую использовать [официальный клиент от гитхаба](https://desktop.github.com/) с ним все будет просто и понятно

Перекачал через git но всеравно ругается Error[Pe020]: identifier "ZCL_HA_DEVICEID_SIMPLE_SENSOR" is undefined D:\@zigbee\@firmware\Z-Stack 3.0.2\Projects\zstack\HomeAutomation\GenericApp\Source\zcl_app_data.c 113 

на строку ZCL_HA_DEVICEID_SIMPLE_SENSOR, //  uint16 AppDeviceId[2];

**Comment by nurikk** [comment]
Вы уверены что HomeAutomation\GenericApp относится к индикатору радиоактивности?

**Comment by v222008** [comment]
> Вы уверены что HomeAutomation\GenericApp относится к индикатору радиоактивности?

Снес Z-Stack 3.0.2 и переустановил его и проблема ушла сама мобой)
